services:
  residente_panel:
    build:
      context: ./residente_panel
      dockerfile: Dockerfile
    container_name: residente_panel
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped